### ISSUE TITLE
how do i make on windows 

### ISSUE THREAD

**Issue by avatar21** [olle/electron-starter#2]
how do i make on windows ??

**Comment by olle** [comment]
I'm sorry, first of all for not answering for an eternity and, secondly, I don't know since I'm not developing on the Windows platform myself.

It should work by using `npm` and Maven `mvn`, doing `nom install` to prepare, building the Java Spring Boot app with `mvn package` and the starting the app with `npm run start`.

Hope this helps. Cheers!
